# Generated by Django 2.2.7 on 2019-12-05 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimerPage', '0003_auto_20191205_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='hour',
            field=models.CharField(default='0', max_length=30),
        ),
        migrations.AlterField(
            model_name='timer',
            name='minute',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AlterField(
            model_name='timer',
            name='second',
            field=models.CharField(default='0', max_length=2),
        ),
    ]
