# Generated by Django 2.2.7 on 2019-11-17 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TimerPage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timer',
            old_name='timer_owner',
            new_name='author',
        ),
    ]
