# Generated by Django 2.2.7 on 2019-12-05 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimerPage', '0002_auto_20191117_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timer',
            name='time',
        ),
        migrations.AddField(
            model_name='timer',
            name='hour',
            field=models.CharField(default='00', max_length=30),
        ),
        migrations.AddField(
            model_name='timer',
            name='minute',
            field=models.CharField(default='00', max_length=2),
        ),
        migrations.AddField(
            model_name='timer',
            name='second',
            field=models.CharField(default='00', max_length=2),
        ),
    ]
