# Generated by Django 2.2.7 on 2019-11-15 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimerPage', '0002_auto_20191115_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='time',
            field=models.CharField(default='00:00:00', max_length=30),
        ),
    ]
